config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'payments#new'
  resources :payments, only: [:index, :show, :new, :create, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  enum status: %i[unresolved created charge_in_progress paid charge_failed reverted delivered expired cancelled]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  def show; end
  def new; end

  def create
    @resp = PaymentCreator.new(payment_create_params).execute
    puts @resp.inspect
  end

  private
  def payment_create_params
    {value: params.dig(:payment, :product_quantity).to_f * 100, request: {ip: request.remote_ip}}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TiendaDss</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/payments/create.html.erb
<% if @resp[:success] %>
<p>La generación de pago ha sido exitosa, para continuar ingresa al siguiente link: </p>
<a class="pay_link" href=<%= @resp[:payment_url] %> target='_self'>Abrir TPaga Wallet</a>
<% else %>
<p> Ha ocurrido un error al generar el pago, por favor intenta nuevamente, si el problema continua,
contacta a nuestro equipo de soporte </p>
<% end %>

app/views/payments/new.html.erb
<h1>Hola, Bienvenido a la tienda DSS</h1>
<%= form_with scope: :payment, url: payments_path, local: true do |form| %>
  <p>Choose the amount of product that you want </p>
  <%= form.label :quantity %><br>
  <%= form.number_field :product_quantity %>

  <%= form.submit "Pay with TPaga"%>
<% end %>